
import com.mycompany.myapp.dto.Automovil;
import com.mycompany.myapp.exceptions.AutomovilDaoException;
import com.mycompany.myapp.jdbc.AutomovilDaoImpl;
import com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException;
import dto.AutomovilPk;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lilol
 */
public class ventanaAutos extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAutos
     */
    public ventanaAutos() throws SQLException, AutomovilDaoException {
        initComponents();
        m = (DefaultTableModel) tblAutomovil.getModel();
        tblAutomovil.setAutoCreateRowSorter(true);
        actualizarTabla();
    }
    private DefaultTableModel m;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnOrganizar = new javax.swing.ButtonGroup();
        pnlRegistro = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomovil = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        rbtnDescendiente = new javax.swing.JRadioButton();
        cmbOpcion = new javax.swing.JComboBox<>();
        rbtnAscendente = new javax.swing.JRadioButton();
        lblTiempo = new javax.swing.JLabel();
        lblTiempoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTipo.setText("Tipo");
        pnlRegistro.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 60, 23));

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMarca.setText("Marca");
        pnlRegistro.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 60, 23));

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblModelo.setText("Modelo");
        pnlRegistro.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 23));

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblColor.setText("Color");
        pnlRegistro.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 60, 23));

        lblAño.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAño.setText("Año");
        pnlRegistro.add(lblAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, 23));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrecio.setText("Precio");
        pnlRegistro.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 23));

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 11, 105, -1));

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 45, 105, -1));

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 79, 105, -1));

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 113, 105, -1));

        txtColor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 147, 105, -1));

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlRegistro.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 181, 105, -1));

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlRegistro.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, -1));

        getContentPane().add(pnlRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, 0, 560, 320));

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAutomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Marca", "Modelo", "Año", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAutomovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutomovilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAutomovil);
        if (tblAutomovil.getColumnModel().getColumnCount() > 0) {
            tblAutomovil.getColumnModel().getColumn(0).setResizable(false);
            tblAutomovil.getColumnModel().getColumn(1).setResizable(false);
            tblAutomovil.getColumnModel().getColumn(2).setResizable(false);
            tblAutomovil.getColumnModel().getColumn(3).setResizable(false);
            tblAutomovil.getColumnModel().getColumn(4).setResizable(false);
            tblAutomovil.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 827, 321));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        gbtnOrganizar.add(rbtnDescendiente);
        rbtnDescendiente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnDescendiente.setText("Descendiente");
        pnlPrincipal.add(rbtnDescendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        cmbOpcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecciona metodo de ordenacion", "bubbleSort", "quickSort", "shellSort", "radixSort" }));
        pnlPrincipal.add(cmbOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 390, -1));

        gbtnOrganizar.add(rbtnAscendente);
        rbtnAscendente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnAscendente.setText("Ascendiente");
        pnlPrincipal.add(rbtnAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 40));

        lblTiempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTiempo.setText("NanoSegundos:");
        pnlPrincipal.add(lblTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        lblTiempoTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTiempoTotal.setText("0000000000");
        pnlPrincipal.add(lblTiempoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        pnlRegistro.setLocation(0, 0);
        pnlPrincipal.setLocation(-850, 0);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (datosValidos()) {
            Automovil dto = new Automovil();
            dto.setTipo(txtTipo.getText());
            dto.setMarca(txtMarca.getText());
            dto.setModelo(txtModelo.getText());
            dto.setAño(Integer.parseInt(txtAño.getText()));
            dto.setColor(txtColor.getText());
            dto.setPrecio(Float.parseFloat(txtPrecio.getText()));

            System.out.println("holi");
            try {
                a.insert(dto);
            } catch (AutomovilDaoException ex) {
                Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                actualizarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (AutomovilDaoException ex) {
                Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("adios");

            pnlRegistro.setLocation(-560, 0);
            pnlPrincipal.setLocation(0, 0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Rellena los datos correctamente");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tblAutomovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutomovilMouseClicked
        try {
            Ordenacion ordenacion = new Ordenacion();
            Automovil total[] = new Automovil[a.findAll().length];
            for (int i = 0; i < total.length; i++) {
                total[i] = a.extraer().get(i);
            }
            tinicio = System.nanoTime();
            if (cmbOpcion.getSelectedIndex() == 1) {
                if (tblAutomovil.getSelectedColumn() == 0 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortString(total, posicion, "tipo");
                } else if (tblAutomovil.getSelectedColumn() == 1 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortString(total, posicion, "marca");
                } else if (tblAutomovil.getSelectedColumn() == 2 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortString(total, posicion, "modelo");
                } else if (tblAutomovil.getSelectedColumn() == 4 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortString(total, posicion, "color");
                } else if (tblAutomovil.getSelectedColumn() == 3 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortNumeros(total, posicion, "año");
                } else if (tblAutomovil.getSelectedColumn() == 5 && rbtnSeleccionado()) {
                    ordenacion.bubbleSortNumeros(total, posicion, "precio");
                }
            } else if (cmbOpcion.getSelectedIndex() == 2) {
                if (tblAutomovil.getSelectedColumn() == 0 && rbtnSeleccionado()) {
                    ordenacion.quickSortString(total, posicion, "tipo");
                } else if (tblAutomovil.getSelectedColumn() == 1 && rbtnSeleccionado()) {
                    ordenacion.quickSortString(total, posicion, "marca");
                } else if (tblAutomovil.getSelectedColumn() == 2 && rbtnSeleccionado()) {
                    ordenacion.quickSortString(total, posicion, "modelo");
                } else if (tblAutomovil.getSelectedColumn() == 4 && rbtnSeleccionado()) {
                    ordenacion.quickSortString(total, posicion, "color");
                } else if (tblAutomovil.getSelectedColumn() == 3 && rbtnSeleccionado()) {
                    ordenacion.quickSortNumeros(total, posicion, "año");
                } else if (tblAutomovil.getSelectedColumn() == 5 && rbtnSeleccionado()) {
                    ordenacion.quickSortNumeros(total, posicion, "precio");
                }
            } else if (cmbOpcion.getSelectedIndex() == 3) {
                if (tblAutomovil.getSelectedColumn() == 0 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "tipo");
                } else if (tblAutomovil.getSelectedColumn() == 1 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "marca");
                } else if (tblAutomovil.getSelectedColumn() == 2 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "modelo");
                } else if (tblAutomovil.getSelectedColumn() == 4 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "color");
                } else if (tblAutomovil.getSelectedColumn() == 3 && rbtnSeleccionado()) {
                    ordenacion.shellNumeros(total, posicion, "año");
                } else if (tblAutomovil.getSelectedColumn() == 5 && rbtnSeleccionado()) {
                    ordenacion.shellNumeros(total, posicion, "precio");
                }
            } else if (cmbOpcion.getSelectedIndex() == 4) {
                if (tblAutomovil.getSelectedColumn() == 0 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "tipo");
                } else if (tblAutomovil.getSelectedColumn() == 1 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "marca");
                } else if (tblAutomovil.getSelectedColumn() == 2 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "modelo");
                } else if (tblAutomovil.getSelectedColumn() == 4 && rbtnSeleccionado()) {
                    ordenacion.shellString(total, posicion, "color");
                } else if (tblAutomovil.getSelectedColumn() == 3 && rbtnSeleccionado()) {
                    actualizarTabla(ordenacion.radixNumeros(a.extraer()));
                } else if (tblAutomovil.getSelectedColumn() == 5 && rbtnSeleccionado()) {
                    ordenacion.shellNumeros(total, posicion, "precio");
                }
            }
            actualizarTabla(total);
            tfin = System.nanoTime();
        } catch (AutomovilDaoException ex) {
            Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        tiempo = tfin - tinicio;
        lblTiempoTotal.setText(tiempo + "");
    }//GEN-LAST:event_tblAutomovilMouseClicked

    private boolean rbtnSeleccionado() {
        if (rbtnAscendente.isSelected()) {
            posicion = 0;
        } else if (rbtnDescendiente.isSelected()) {
            posicion = 1;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un radiobutton");
            return false;
        }
        return true;
    }

    public void actualizarTabla(List<Automovil> b){
           m.setRowCount(0);

        Object obj[] = new Object[6];
        for (int i = 0; i < b.size(); i++) {
            for (int j = 0; j < 6; j++) {
                switch (j) {
                    case 0:
                        obj[0] = b.get(i).getTipo();
                        break;
                    case 1:
                        obj[1] = b.get(i).getMarca();
                        break;
                    case 2:
                        obj[2] = b.get(i).getModelo();
                        break;
                    case 3:
                        obj[3] = b.get(i).getAño();
                        break;
                    case 4:
                        obj[4] = b.get(i).getColor();
                        break;
                    case 5:
                        obj[5] = b.get(i).getPrecio();
                        break;
                }
            }
            m.addRow(obj);
        }     
    }
    public void actualizarTabla(Automovil[] A) {
        m.setRowCount(0);

        Object obj[] = new Object[6];
        for (int i = 0; i < A.length; i++) {
            for (int j = 0; j < 6; j++) {
                switch (j) {
                    case 0:
                        obj[0] = A[i].getTipo();
                        break;
                    case 1:
                        obj[1] = A[i].getMarca();
                        break;
                    case 2:
                        obj[2] = A[i].getModelo();
                        break;
                    case 3:
                        obj[3] = A[i].getAño();
                        break;
                    case 4:
                        obj[4] = A[i].getColor();
                        break;
                    case 5:
                        obj[5] = A[i].getPrecio();
                        break;
                }
            }
            m.addRow(obj);
        }
    }

    public void actualizarTabla() throws SQLException, AutomovilDaoException {
        m.setRowCount(0);

        Object obj[] = new Object[6];
        for (int i = 0; i < a.findAll().length; i++) {
            for (int j = 0; j < 6; j++) {
                switch (j) {
                    case 0:
                        obj[0] = a.extraer().get(i).getTipo();
                        System.out.println(a.extraer().get(i).getTipo());
                        break;
                    case 1:
                        obj[1] = a.extraer().get(i).getMarca();
                        break;
                    case 2:
                        obj[2] = a.extraer().get(i).getModelo();
                        break;
                    case 3:
                        obj[3] = a.extraer().get(i).getAño();
                        break;
                    case 4:
                        obj[4] = a.extraer().get(i).getColor();
                        break;
                    case 5:
                        obj[5] = a.extraer().get(i).getPrecio();
                        break;
                }
            }
            m.addRow(obj);
        }

    }

    private boolean verificarTipo(String tipo) {
        return tipo.length() > 0;
    }

    private boolean verificarMarca(String marca) {
        return marca.length() > 0;
    }

    private boolean verificarModelo(String modelo) {
        return modelo.length() > 0;
    }

    private boolean verificarAño(int año) {
        return año >= 1900 && año <= 2019;
    }

    private boolean verificarColor(String color) {
        return color.length() > 0;
    }

    private boolean verificarPrecio(float precio) {
        return precio > 0;
    }

    private boolean datosValidos() {
        return verificarTipo(txtTipo.getText()) && verificarMarca(txtMarca.getText()) && verificarModelo(txtModelo.getText()) && verificarAño(Integer.parseInt(txtAño.getText())) && verificarColor(txtColor.getText()) && verificarPrecio(Float.parseFloat(txtPrecio.getText()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new ventanaAutos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (AutomovilDaoException ex) {
                    Logger.getLogger(ventanaAutos.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    int posicion;
    AutomovilDaoImpl a = new AutomovilDaoImpl();
    long tinicio, tfin, tiempo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.ButtonGroup gbtnOrganizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempoTotal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JRadioButton rbtnAscendente;
    private javax.swing.JRadioButton rbtnDescendiente;
    private javax.swing.JTable tblAutomovil;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
