/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dto;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the automovil table.
 */
public class AutomovilPk implements Serializable
{
	protected int automovilcol;

	/** 
	 * This attribute represents whether the primitive attribute automovilcol is null.
	 */
	protected boolean automovilcolNull;

	/** 
	 * Sets the value of automovilcol
	 */
	public void setAutomovilcol(int automovilcol)
	{
		this.automovilcol = automovilcol;
	}

	/** 
	 * Gets the value of automovilcol
	 */
	public int getAutomovilcol()
	{
		return automovilcol;
	}

	/**
	 * Method 'AutomovilPk'
	 * 
	 */
	public AutomovilPk()
	{
	}

	/**
	 * Method 'AutomovilPk'
	 * 
	 * @param automovilcol
	 */
	public AutomovilPk(final int automovilcol)
	{
		this.automovilcol = automovilcol;
	}

	/** 
	 * Sets the value of automovilcolNull
	 */
	public void setAutomovilcolNull(boolean automovilcolNull)
	{
		this.automovilcolNull = automovilcolNull;
	}

	/** 
	 * Gets the value of automovilcolNull
	 */
	public boolean isAutomovilcolNull()
	{
		return automovilcolNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AutomovilPk)) {
			return false;
		}
		
		final AutomovilPk _cast = (AutomovilPk) _other;
		if (automovilcol != _cast.automovilcol) {
			return false;
		}
		
		if (automovilcolNull != _cast.automovilcolNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + automovilcol;
		_hashCode = 29 * _hashCode + (automovilcolNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.antimfr.automovil.dto.AutomovilPk: " );
		ret.append( "automovilcol=" + automovilcol );
		return ret.toString();
	}

}
